package com.example

/**
 * Data model for Arabic letters with their 4 contextual positional forms:
 * Isolated, Initial, Medial, and Final.
 */
data class ArabicLetter(
  val id: Int,
  val letter: String,
  val nameEn: String,
  val nameBn: String,
  val nameAr: String,
  val isolated: String,
  val initial: String,
  val medial: String,
  val finalForm: String,
  val phonetic: String,
  val makhrajEn: String,
  val makhrajBn: String,
  val makhrajAr: String,
  val sampleWord: String,
  val sampleWordTranslation: String
) {
  fun getName(lang: String): String = when (lang) {
    "EN" -> nameEn
    "AR" -> nameAr
    else -> nameBn
  }

  fun getMakhraj(lang: String): String = when (lang) {
    "EN" -> makhrajEn
    "AR" -> makhrajAr
    else -> makhrajBn
  }
}

object ArabicAlphabetRepository {
  val letters: List<ArabicLetter> = listOf(
    ArabicLetter(
      id = 1,
      letter = "ا",
      nameEn = "Alif",
      nameBn = "আলিফ",
      nameAr = "ألف",
      isolated = "ا",
      initial = "اـ",
      medial = "ـا",
      finalForm = "ـا",
      phonetic = "a / ā",
      makhrajEn = "Empty space in the mouth & throat (Jawf)",
      makhrajBn = "মুখের খালি জায়গা (জওফ) থেকে উৎপন্ন হয়",
      makhrajAr = "الجوف (الخلاء في الحلق والفم)",
      sampleWord = "أَمَلٌ",
      sampleWordTranslation = "Hope / আশা"
    ),
    ArabicLetter(
      id = 2,
      letter = "ب",
      nameEn = "Ba",
      nameBn = "বা",
      nameAr = "باء",
      isolated = "ب",
      initial = "بـ",
      medial = "ـبـ",
      finalForm = "ـب",
      phonetic = "b",
      makhrajEn = "Between the wet inner part of both lips",
      makhrajBn = "দুই ঠোঁটের ভেজা অংশ মিলিত হয়ে",
      makhrajAr = "بين الشفتين بانطباقهما مع بلل",
      sampleWord = "بَابٌ",
      sampleWordTranslation = "Door / দরজা"
    ),
    ArabicLetter(
      id = 3,
      letter = "ت",
      nameEn = "Ta",
      nameBn = "তা",
      nameAr = "تاء",
      isolated = "ت",
      initial = "تـ",
      medial = "ـتـ",
      finalForm = "ـت",
      phonetic = "t",
      makhrajEn = "Tip of tongue touching the base of upper two front teeth",
      makhrajBn = "জিহ্বার ডগা উপরের দুই দাঁতের গোঁড়ায় লাগিয়ে",
      makhrajAr = "طرف اللسان مع أصول الثنايا العليا",
      sampleWord = "تَاجٌ",
      sampleWordTranslation = "Crown / মুকুট"
    ),
    ArabicLetter(
      id = 4,
      letter = "ث",
      nameEn = "Tha",
      nameBn = "ছা",
      nameAr = "ثاء",
      isolated = "ث",
      initial = "ثـ",
      medial = "ـثـ",
      finalForm = "ـث",
      phonetic = "th",
      makhrajEn = "Tip of tongue touching the edges of upper two front teeth softly",
      makhrajBn = "জিহ্বার ডগা উপরের দুই দাঁতের কিনারায় নরমভাবে লাগিয়ে",
      makhrajAr = "طرف اللسان مع أطراف الثنايا العليا برقة",
      sampleWord = "ثَمَرٌ",
      sampleWordTranslation = "Fruit / ফল"
    ),
    ArabicLetter(
      id = 5,
      letter = "ج",
      nameEn = "Jim",
      nameBn = "জীম",
      nameAr = "جيم",
      isolated = "ج",
      initial = "جـ",
      medial = "ـجـ",
      finalForm = "ـج",
      phonetic = "j",
      makhrajEn = "Middle of the tongue touching the roof of the mouth",
      makhrajBn = "জিহ্বার মধ্যভাগ সোজা উপরের তালুতে লাগিয়ে",
      makhrajAr = "وسط اللسان مع ما يحاذيه من الحنك الأعلى",
      sampleWord = "جَمَلٌ",
      sampleWordTranslation = "Camel / উট"
    ),
    ArabicLetter(
      id = 6,
      letter = "ح",
      nameEn = "Ha",
      nameBn = "হা (বড় হা)",
      nameAr = "حاء",
      isolated = "ح",
      initial = "حـ",
      medial = "ـحـ",
      finalForm = "ـح",
      phonetic = "ḥ",
      makhrajEn = "Middle of the throat",
      makhrajBn = "হলকের (গলার) মধ্যভাগ থেকে পরিষ্কারভাবে",
      makhrajAr = "وسط الحلق",
      sampleWord = "حَدِيقَةٌ",
      sampleWordTranslation = "Garden / বাগান"
    ),
    ArabicLetter(
      id = 7,
      letter = "خ",
      nameEn = "Kha",
      nameBn = "খ",
      nameAr = "خاء",
      isolated = "خ",
      initial = "خـ",
      medial = "ـخـ",
      finalForm = "ـخ",
      phonetic = "kh",
      makhrajEn = "Top part of the throat near the mouth",
      makhrajBn = "হলকের (গলার) শেষভাগ মুখের দিক থেকে",
      makhrajAr = "أدنى الحلق مما يلي الفم",
      sampleWord = "خُبْزٌ",
      sampleWordTranslation = "Bread / রুটি"
    ),
    ArabicLetter(
      id = 8,
      letter = "د",
      nameEn = "Dal",
      nameBn = "দাল",
      nameAr = "دال",
      isolated = "د",
      initial = "دـ",
      medial = "ـد",
      finalForm = "ـد",
      phonetic = "d",
      makhrajEn = "Tip of tongue with the roots of upper front teeth",
      makhrajBn = "জিহ্বার ডগা উপরের সামনের দুই দাঁতের গোঁড়ায় লাগিয়ে",
      makhrajAr = "طرف اللسان مع أصول الثنايا العليا",
      sampleWord = "دَرْسٌ",
      sampleWordTranslation = "Lesson / পাঠ"
    ),
    ArabicLetter(
      id = 9,
      letter = "ذ",
      nameEn = "Dhal",
      nameBn = "যাল",
      nameAr = "ذال",
      isolated = "ذ",
      initial = "ذـ",
      medial = "ـذ",
      finalForm = "ـذ",
      phonetic = "dh",
      makhrajEn = "Tip of tongue touching the edges of upper front teeth",
      makhrajBn = "জিহ্বার ডগা উপরের সামনের দুই দাঁতের কিনারার সাথে",
      makhrajAr = "طرف اللسان مع أطراف الثنايا العليا",
      sampleWord = "ذَهَبٌ",
      sampleWordTranslation = "Gold / স্বর্ণ"
    ),
    ArabicLetter(
      id = 10,
      letter = "ر",
      nameEn = "Ra",
      nameBn = "র",
      nameAr = "راء",
      isolated = "ر",
      initial = "رـ",
      medial = "ـر",
      finalForm = "ـر",
      phonetic = "r",
      makhrajEn = "Tip of tongue near the edge with gums of upper teeth",
      makhrajBn = "জিহ্বার ডগার পিঠ উপরের দাঁতের মাড়ির তালুর সাথে",
      makhrajAr = "طرف اللسان مع لثة الثنايا العليا مائلاً لظهره",
      sampleWord = "رَحْمَةٌ",
      sampleWordTranslation = "Mercy / রহমত"
    ),
    ArabicLetter(
      id = 11,
      letter = "ز",
      nameEn = "Zay",
      nameBn = "ঝা",
      nameAr = "زاي",
      isolated = "ز",
      initial = "زـ",
      medial = "ـز",
      finalForm = "ـز",
      phonetic = "z",
      makhrajEn = "Tip of tongue with the plates of lower front teeth",
      makhrajBn = "জিহ্বার ডগা নিচের সামনের দুই দাঁতের সাথে সিস্ দিয়ে",
      makhrajAr = "طرف اللسان فوق الثنايا السفلى بصفير",
      sampleWord = "زَهْرَةٌ",
      sampleWordTranslation = "Flower / ফুল"
    ),
    ArabicLetter(
      id = 12,
      letter = "س",
      nameEn = "Sin",
      nameBn = "সীন",
      nameAr = "سين",
      isolated = "س",
      initial = "سـ",
      medial = "ـسـ",
      finalForm = "ـس",
      phonetic = "s",
      makhrajEn = "Tip of tongue directly above lower front teeth",
      makhrajBn = "জিহ্বার ডগা নিচের সামনের দুই দাঁতের ভেতরের অংশে",
      makhrajAr = "طرف اللسان مع ما فوق الثنايا السفلى",
      sampleWord = "سَلَامٌ",
      sampleWordTranslation = "Peace / শান্তি"
    ),
    ArabicLetter(
      id = 13,
      letter = "ش",
      nameEn = "Shin",
      nameBn = "শীন",
      nameAr = "شين",
      isolated = "ش",
      initial = "شـ",
      medial = "ـشـ",
      finalForm = "ـش",
      phonetic = "sh",
      makhrajEn = "Middle of the tongue against the palate with spreading air",
      makhrajBn = "জিহ্বার মধ্যভাগ তালুর সাথে বাতাসে ছড়িয়ে",
      makhrajAr = "وسط اللسان مع الحنك الأعلى مع تفشي",
      sampleWord = "شَمْسٌ",
      sampleWordTranslation = "Sun / সূর্য"
    ),
    ArabicLetter(
      id = 14,
      letter = "ص",
      nameEn = "Sad",
      nameBn = "সোয়াদ",
      nameAr = "صاد",
      isolated = "ص",
      initial = "صـ",
      medial = "ـصـ",
      finalForm = "ـص",
      phonetic = "ṣ",
      makhrajEn = "Tip of tongue above lower front teeth (Heavy)",
      makhrajBn = "জিহ্বার ডগা নিচের দাঁতের সাথে মুখ ভর্তি ভারী উচ্চারণে",
      makhrajAr = "طرف اللسان مع أسفل صفحتي الثنيتين مع إطباق",
      sampleWord = "صَبْرٌ",
      sampleWordTranslation = "Patience / ধৈর্য"
    ),
    ArabicLetter(
      id = 15,
      letter = "ض",
      nameEn = "Dad",
      nameBn = "দোয়াদ",
      nameAr = "ضاد",
      isolated = "ض",
      initial = "ضـ",
      medial = "ـضـ",
      finalForm = "ـض",
      phonetic = "ḍ",
      makhrajEn = "Side of tongue touching upper left or right molar teeth",
      makhrajBn = "জিহ্বার পার্শ্বভাগ উপরের মাড়ির দাঁতের গোঁড়ার সাথে",
      makhrajAr = "إحدى حافتي اللسان مع الأضراس العليا",
      sampleWord = "ضَوْءٌ",
      sampleWordTranslation = "Light / আলো"
    ),
    ArabicLetter(
      id = 16,
      letter = "ط",
      nameEn = "Ta' (Heavy)",
      nameBn = "তোয়া",
      nameAr = "طاء",
      isolated = "ط",
      initial = "طـ",
      medial = "ـطـ",
      finalForm = "ـط",
      phonetic = "ṭ",
      makhrajEn = "Tip of tongue with the base of upper teeth with fullness",
      makhrajBn = "জিহ্বার ডগা উপরের দাঁতের গোঁড়ায় মুখ গোল করে ভারীভাবে",
      makhrajAr = "طرف اللسان مع أصول الثنايا العليا باستعلاء",
      sampleWord = "طَالِبٌ",
      sampleWordTranslation = "Student / ছাত্র"
    ),
    ArabicLetter(
      id = 17,
      letter = "ظ",
      nameEn = "Za' (Heavy)",
      nameBn = "যোয়া",
      nameAr = "ظاء",
      isolated = "ظ",
      initial = "ظـ",
      medial = "ـظـ",
      finalForm = "ـظ",
      phonetic = "ẓ",
      makhrajEn = "Tip of tongue touching edges of upper teeth with fullness",
      makhrajBn = "জিহ্বার ডগা উপরের দাঁতের কিনারায় ভারী উচ্চারণে",
      makhrajAr = "طرف اللسان مع أطراف الثنايا العليا باستعلاء",
      sampleWord = "ظِلٌّ",
      sampleWordTranslation = "Shadow / ছায়া"
    ),
    ArabicLetter(
      id = 18,
      letter = "ع",
      nameEn = "'Ayn",
      nameBn = "আইন",
      nameAr = "عين",
      isolated = "ع",
      initial = "عـ",
      medial = "ـعـ",
      finalForm = "ـع",
      phonetic = "ʿ",
      makhrajEn = "Middle of the throat with deep contraction",
      makhrajBn = "হলকের মধ্যভাগ গভীর সংকুচিত করে",
      makhrajAr = "وسط الحلق بعمق",
      sampleWord = "عِلْمٌ",
      sampleWordTranslation = "Knowledge / জ্ঞান"
    ),
    ArabicLetter(
      id = 19,
      letter = "غ",
      nameEn = "Ghayn",
      nameBn = "গাইন",
      nameAr = "غين",
      isolated = "غ",
      initial = "غـ",
      medial = "ـغـ",
      finalForm = "ـغ",
      phonetic = "gh",
      makhrajEn = "Top of the throat near mouth with gurgle",
      makhrajBn = "হলকের শুরুর অংশ মুখের কাছে ভারীভাবে",
      makhrajAr = "أدنى الحلق مما يلي الفم باستعلاء",
      sampleWord = "غَيْبٌ",
      sampleWordTranslation = "Unseen / অদৃশ্যের বিষয়"
    ),
    ArabicLetter(
      id = 20,
      letter = "ف",
      nameEn = "Fa",
      nameBn = "ফা",
      nameAr = "فاء",
      isolated = "ف",
      initial = "فـ",
      medial = "ـفـ",
      finalForm = "ـف",
      phonetic = "f",
      makhrajEn = "Edges of upper front teeth with the inside wet lower lip",
      makhrajBn = "উপরের সামনের দাঁতের পেট নিচের ঠোঁটের ভেতরের অংশে",
      makhrajAr = "أطراف الثنايا العليا مع باطن الشفة السفلى",
      sampleWord = "فَجْرٌ",
      sampleWordTranslation = "Dawn / ভোর"
    ),
    ArabicLetter(
      id = 21,
      letter = "ق",
      nameEn = "Qaf",
      nameBn = "ক্বাফ",
      nameAr = "قاف",
      isolated = "ق",
      initial = "قـ",
      medial = "ـقـ",
      finalForm = "ـق",
      phonetic = "q",
      makhrajEn = "Deep back of tongue against the soft palate",
      makhrajBn = "জিহ্বার গোঁড়া তার বরাবর উপরের নরম তালুতে লাগিয়ে",
      makhrajAr = "أقصى اللسان مع الحنك اللحمي الأعلى",
      sampleWord = "قَلْبٌ",
      sampleWordTranslation = "Heart / হৃদয়"
    ),
    ArabicLetter(
      id = 22,
      letter = "ك",
      nameEn = "Kaf",
      nameBn = "কাফ",
      nameAr = "كاف",
      isolated = "ك",
      initial = "كـ",
      medial = "ـكـ",
      finalForm = "ـك",
      phonetic = "k",
      makhrajEn = "Back of tongue against hard and soft palate boundary",
      makhrajBn = "জিহ্বার গোঁড়া থেকে একটু এগিয়ে তালুতে নরমভাবে",
      makhrajAr = "أقصى اللسان أسفل من القاف قليلاً",
      sampleWord = "كِتَابٌ",
      sampleWordTranslation = "Book / বই"
    ),
    ArabicLetter(
      id = 23,
      letter = "ل",
      nameEn = "Lam",
      nameBn = "লাম",
      nameAr = "لام",
      isolated = "ل",
      initial = "لـ",
      medial = "ـلـ",
      finalForm = "ـل",
      phonetic = "l",
      makhrajEn = "From side of tongue to its tip with the upper gums",
      makhrajBn = "জিহ্বার অগ্রভাগের কিনারা সামনের দাঁতের মাড়ির সাথে",
      makhrajAr = "أدنى حافة اللسان إلى منتهى طرفه مع لثة الأسنان العليا",
      sampleWord = "لَيْلٌ",
      sampleWordTranslation = "Night / রাত"
    ),
    ArabicLetter(
      id = 24,
      letter = "م",
      nameEn = "Mim",
      nameBn = "মীম",
      nameAr = "ميم",
      isolated = "م",
      initial = "مـ",
      medial = "ـمـ",
      finalForm = "ـم",
      phonetic = "m",
      makhrajEn = "Both lips pressed together lightly with nasal resonance",
      makhrajBn = "দুই ঠোঁটের শুষ্ক অংশ হালকা চাপ দিয়ে গুন্নাহ সহ",
      makhrajAr = "بين الشفتين بانطباقهما مع غنة الخيشوم",
      sampleWord = "مَسْجِدٌ",
      sampleWordTranslation = "Mosque / মসজিদ"
    ),
    ArabicLetter(
      id = 25,
      letter = "ن",
      nameEn = "Nun",
      nameBn = "নূন",
      nameAr = "نون",
      isolated = "ن",
      initial = "نـ",
      medial = "ـنـ",
      finalForm = "ـن",
      phonetic = "n",
      makhrajEn = "Tip of tongue with the upper gums with nasal ghunnah",
      makhrajBn = "জিহ্বার ডগা উপরের দাঁতের মাড়ির সাথে গুন্নাহ সহ",
      makhrajAr = "طرف اللسان مع لثة الثنايا العليا مع غنة",
      sampleWord = "نُورٌ",
      sampleWordTranslation = "Divine Light / নূর বা জ্যোতি"
    ),
    ArabicLetter(
      id = 26,
      letter = "و",
      nameEn = "Waw",
      nameBn = "ওয়াও",
      nameAr = "واو",
      isolated = "و",
      initial = "وـ",
      medial = "ـو",
      finalForm = "ـو",
      phonetic = "w / ū",
      makhrajEn = "Rounding both lips leaving a small circular opening",
      makhrajBn = "দুই ঠোঁট গোল করে সামান্য ফাঁকা রেখে",
      makhrajAr = "ضم الشفتين مع فرجة يسيرة",
      sampleWord = "وَرْدَةٌ",
      sampleWordTranslation = "Rose / গোলাপ"
    ),
    ArabicLetter(
      id = 27,
      letter = "هـ",
      nameEn = "Ha (Small)",
      nameBn = "হা (গোল হা)",
      nameAr = "هاء",
      isolated = "هـ",
      initial = "هـ",
      medial = "ـهـ",
      finalForm = "ـه",
      phonetic = "h",
      makhrajEn = "Deepest part of the throat near chest",
      makhrajBn = "হলকের একেবারে শুরু সিনার দিক থেকে",
      makhrajAr = "أقصى الحلق مما يلي الصدر",
      sampleWord = "هُدًى",
      sampleWordTranslation = "Guidance / হেদায়েত"
    ),
    ArabicLetter(
      id = 28,
      letter = "ء",
      nameEn = "Hamza",
      nameBn = "হামযা",
      nameAr = "همزة",
      isolated = "ء",
      initial = "ء",
      medial = "ـء",
      finalForm = "ـء",
      phonetic = "ʾ (glottal stop)",
      makhrajEn = "Deepest part of the throat with a clear sound cut",
      makhrajBn = "হলকের শেষভাগ থেকে স্পষ্ট ধ্বনি কর্তন",
      makhrajAr = "أقصى الحلق مع انحباس الصوت",
      sampleWord = "أَمَانَةٌ",
      sampleWordTranslation = "Trust / আমানত"
    ),
    ArabicLetter(
      id = 29,
      letter = "ي",
      nameEn = "Ya",
      nameBn = "ইয়া",
      nameAr = "ياء",
      isolated = "ي",
      initial = "يـ",
      medial = "ـيـ",
      finalForm = "ـي",
      phonetic = "y / ī",
      makhrajEn = "Middle of the tongue against the palate without constriction",
      makhrajBn = "জিহ্বার মধ্যভাগ উপরের তালুর সাথে আলতোভাবে",
      makhrajAr = "وسط اللسان مع الحنك الأعلى",
      sampleWord = "يَقِينٌ",
      sampleWordTranslation = "Certainty / দৃঢ় বিশ্বাস"
    )
  )
}
